import {
	ComputerDesktopIcon,
	CommandLineIcon,
	CodeBracketIcon,
	UserGroupIcon,
	UsersIcon,
	EnvelopeIcon,
	WalletIcon,
	CogIcon,
	ChatBubbleLeftRightIcon,
	ChatBubbleOvalLeftEllipsisIcon,
	PhoneArrowDownLeftIcon,
	AcademicCapIcon,
	WrenchScrewdriverIcon,
	PresentationChartBarIcon,
} from "@heroicons/vue/24/solid";

export const iconsObject = {
	"Account Manager": PresentationChartBarIcon,
	"Admin Executive": PhoneArrowDownLeftIcon,
	"Call Centre": PhoneArrowDownLeftIcon,
	"Consultancy Director": UsersIcon,
	Consultant: ChatBubbleOvalLeftEllipsisIcon,
	Developer: CodeBracketIcon,
	"Engineering Director": CogIcon,
	"Finance Executive": WalletIcon,
	"Finance Director": WalletIcon,
	"Finance Manager": WalletIcon,
	"HR Director": UserGroupIcon,
	"HR Executive": UserGroupIcon,
	"IT Analyst": CommandLineIcon,
	"IT Director": CommandLineIcon,
	"Junior Engineer": CogIcon,
	"L&D Executive": AcademicCapIcon,
	"Ops Planning Exec": WrenchScrewdriverIcon,
	"Sales Director": ChatBubbleOvalLeftEllipsisIcon,
	"Sales Manager": ChatBubbleOvalLeftEllipsisIcon,
	"Senior Engineer": CogIcon,
	"Solutioning Director": PresentationChartBarIcon,
	"Support Engineer": CogIcon,
};
